# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dealog_parser_add_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Input_db import Input_db
from DataGrabber import DataGrabber

class Ui_Dialog_parser_area(object):

    def __init__(self, Mainwindow):
        self.Mainwindow = Mainwindow

    def click_on_tab_1(self, dialog): #нажатие на кнопку OK

        if len(self.name_area.text()) == 0:
            return

        print(self.name_area.text())

        #print(self.comboBox.currentText()) #1
        #print(self.comboBox_2.currentText()) #2
        #print(self.comboBox_3.currentText()) #3
        #print(self.comboBox_4.currentText()) #4
        #print(self.spinBox.value()) #1.1
        #print(self.spinBox_2.value()) #1.2
        #print(self.spinBox_3.value()) #1.3
        #print(self.spinBox_4.value()) #3.1
        #print(self.spinBox_5.value()) #3.2
        #print(self.spinBox_6.value()) #3.3
        #print(self.spinBox_7.value()) #2.1
        #print(self.spinBox_8.value()) #2.2
        #print(self.spinBox_9.value()) #2.3
        #print(self.spinBox_10.value()) #4.1
        #print(self.spinBox_11.value()) #4.2
        #print(self.spinBox_12.value()) #4.3

        print("Левый верхний угол: " + self.comboBox_NS_1.currentText() + " " +
              str(self.spinBox_h_1.value()) +
              " Градусов " + str(self.spinBox_m_1.value()) +
              " Минут " + str(self.spinBox_s_1.value()) +
              " Секунд\n" +
              self.comboBox_WE_2.currentText() + " " +
              str(self.spinBox_h_2.value()) +
              " Градусов " + str(self.spinBox_m_2.value()) +
              " Минут " + str(self.spinBox_s_2.value()) +
              " Секунд\n")
        print("Правый нижний угол: " + self.comboBox_NS_3.currentText() + " " +
              str(self.spinBox_h_3.value()) +
              " Градусов " + str(self.spinBox_m_3.value()) +
              " Минут " + str(self.spinBox_s_3.value()) +
              " Секунд\n" +
              self.comboBox_WE_4.currentText() + " " +
              str(self.spinBox_h_4.value()) +
              " Градусов " + str(self.spinBox_m_4.value()) +
              " Минут " + str(self.spinBox_s_4.value()) +
              " Секунд\n")

        area = []
        top = {
            "x": {
                "degree": 131,
                "minute": 24,
                "second": 54
            },
            "y": {
                "degree": 43,
                "minute": 7,
                "second": 23
            }
        }
        area.append(top)
        bot = {
            "x": {
                "degree": 131,
                "minute": 57,
                "second": 30
            },
            "y": {
                "degree": 43,
                "minute": 2,
                "second": 57
            }
        }
        area.append(bot)
        DataGrabber.start_scan(area)
        self.Mainwindow.remake_table_parser()
        self.Mainwindow.statusbar.showMessage("")
        area = {
            'area_name': str(self.name_area.text()),
            'latitude_l_u': 131.4075,
            'longitude_l_u': 43.1210,
            'latitude_r_d': 131.9650,
            'longitude_r_d': 43.0488
        }
        Input_db.input_for_base_area(area)

        dialog.reject()

    def click_on_tab_2(self, dialog): #нажатие на кнопку OK

        if len(self.name_area.text()) == 0:
            return

        print(self.name_area.text())

        print("Левая широта: " + str(self.doubleSpinBox_lati_l_1.value()))
        print("Верхняя долгота: " + str(self.doubleSpinBox_long_u_2.value()))
        print("Правая широта: " + str(self.doubleSpinBox_lati_r_3.value()))
        print("Нижняя долгота: " + str(self.doubleSpinBox_long_d_4.value()))
        area = {
            'area_name': str(self.name_area.text()),
            'latitude_l_u': self.doubleSpinBox_lati_l_1.value(),
            'longitude_l_u': self.doubleSpinBox_long_u_2.value(),
            'latitude_r_d': self.doubleSpinBox_lati_r_3.value(),
            'longitude_r_d': self.doubleSpinBox_long_d_4.value()
        }
        Input_db.input_for_base_area(area)
        
        area = []
        top = {
            "x": {
                "degree": 131,
                "minute": 24,
                "second": 54
            },
            "y": {
                "degree": 43,
                "minute": 7,
                "second": 23
            }
        }
        area.append(top)
        bot = {
            "x": {
                "degree": 131,
                "minute": 57,
                "second": 30
            },
            "y": {
                "degree": 43,
                "minute": 2,
                "second": 57
            }
        }
        area.append(bot)
        DataGrabber.start_scan(area)

        dialog.reject()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 420)
        Dialog.setMinimumSize(QtCore.QSize(640, 420))
        Dialog.setMaximumSize(QtCore.QSize(640, 420))
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.name_area = QtWidgets.QLineEdit(self.layoutWidget)
        self.name_area.setObjectName("name_area")
        self.horizontalLayout_3.addWidget(self.name_area)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(619, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(619, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 611, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(22)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_NS_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_NS_1.setObjectName("comboBox_NS_1")
        self.comboBox_NS_1.addItem("")
        self.comboBox_NS_1.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_NS_1)
        self.spinBox_h_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_h_1.setMinimum(-1000)
        self.spinBox_h_1.setMaximum(1000)
        self.spinBox_h_1.setObjectName("spinBox_h_1")
        self.horizontalLayout.addWidget(self.spinBox_h_1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox_m_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_m_1.setMinimum(-1000)
        self.spinBox_m_1.setMaximum(1000)
        self.spinBox_m_1.setObjectName("spinBox_m_1")
        self.horizontalLayout.addWidget(self.spinBox_m_1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBox_s_1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_s_1.setMinimum(-1000)
        self.spinBox_s_1.setMaximum(1000)
        self.spinBox_s_1.setObjectName("spinBox_s_1")
        self.horizontalLayout.addWidget(self.spinBox_s_1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(108, 0))
        self.label_11.setMaximumSize(QtCore.QSize(108, 16777215))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.comboBox_WE_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_WE_2.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_WE_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_WE_2.setObjectName("comboBox_WE_2")
        self.comboBox_WE_2.addItem("")
        self.comboBox_WE_2.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_WE_2)
        self.spinBox_h_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_h_2.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_h_2.setMaximumSize(QtCore.QSize(12423525, 16777215))
        self.spinBox_h_2.setObjectName("spinBox_h_2")
        self.spinBox_h_2.setMinimum(-1000)
        self.spinBox_h_2.setMaximum(1000)
        self.horizontalLayout_4.addWidget(self.spinBox_h_2)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.spinBox_m_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_m_2.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_m_2.setMaximumSize(QtCore.QSize(1254141, 16777215))
        self.spinBox_m_2.setObjectName("spinBox_m_2")
        self.spinBox_m_2.setMinimum(-1000)
        self.spinBox_m_2.setMaximum(1000)
        self.horizontalLayout_4.addWidget(self.spinBox_m_2)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.spinBox_s_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_s_2.setObjectName("spinBox_s_2")
        self.spinBox_s_2.setMinimum(-1000)
        self.spinBox_s_2.setMaximum(1000)
        self.horizontalLayout_4.addWidget(self.spinBox_s_2)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboBox_NS_3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_NS_3.setObjectName("comboBox_NS_3")
        self.comboBox_NS_3.addItem("")
        self.comboBox_NS_3.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_NS_3)
        self.spinBox_h_3 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_h_3.setMinimum(-1000)
        self.spinBox_h_3.setMaximum(1000)
        self.spinBox_h_3.setObjectName("spinBox_h_3")
        self.spinBox_h_3.setMinimum(-1000)
        self.spinBox_h_3.setMaximum(1000)
        self.horizontalLayout_2.addWidget(self.spinBox_h_3)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spinBox_m_3 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_m_3.setMinimum(-1000)
        self.spinBox_m_3.setMaximum(1000)
        self.spinBox_m_3.setObjectName("spinBox_m_3")
        self.spinBox_m_3.setMinimum(-1000)
        self.spinBox_m_3.setMaximum(1000)
        self.horizontalLayout_2.addWidget(self.spinBox_m_3)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.spinBox_s_3 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_s_3.setMinimum(-1000)
        self.spinBox_s_3.setMaximum(1000)
        self.spinBox_s_3.setObjectName("spinBox_s_3")
        self.spinBox_s_3.setMinimum(-1000)
        self.spinBox_s_3.setMaximum(1000)
        self.horizontalLayout_2.addWidget(self.spinBox_s_3)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(110, 0))
        self.label_15.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.comboBox_WE_4 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_WE_4.setObjectName("comboBox_WE_4")
        self.comboBox_WE_4.addItem("")
        self.comboBox_WE_4.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_WE_4)
        self.spinBox_h_4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_h_4.setObjectName("spinBox_h_4")
        self.spinBox_h_4.setMinimum(-1000)
        self.spinBox_h_4.setMaximum(1000)
        self.horizontalLayout_5.addWidget(self.spinBox_h_4)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.spinBox_m_4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_m_4.setObjectName("spinBox_m_4")
        self.spinBox_m_4.setMinimum(-1000)
        self.spinBox_m_4.setMaximum(1000)
        self.horizontalLayout_5.addWidget(self.spinBox_m_4)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.spinBox_s_4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_s_4.setObjectName("spinBox_s_4")
        self.spinBox_m_4.setMinimum(-1000)
        self.spinBox_m_4.setMaximum(1000)
        self.horizontalLayout_5.addWidget(self.spinBox_s_4)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_5.addWidget(self.label_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.buttonBox_tab_1 = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox_tab_1.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_tab_1.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_tab_1.setObjectName("buttonBox_tab_1")
        self.verticalLayout_2.addWidget(self.buttonBox_tab_1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 611, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(22)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_23.setMinimumSize(QtCore.QSize(10, 0))
        self.label_23.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_6.addWidget(self.label_23)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setMinimumSize(QtCore.QSize(91, 0))
        self.label_19.setMaximumSize(QtCore.QSize(91, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.doubleSpinBox_lati_l_1 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_lati_l_1.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_lati_l_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_lati_l_1.setDecimals(4)
        self.doubleSpinBox_lati_l_1.setObjectName("doubleSpinBox_lati_l_1")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_lati_l_1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setMinimumSize(QtCore.QSize(10, 0))
        self.label_24.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_7.addWidget(self.label_24)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setMinimumSize(QtCore.QSize(91, 0))
        self.label_20.setMaximumSize(QtCore.QSize(91, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.doubleSpinBox_long_u_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_long_u_2.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_long_u_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_long_u_2.setDecimals(4)
        self.doubleSpinBox_long_u_2.setObjectName("doubleSpinBox_long_u_2")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_long_u_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_25.setMinimumSize(QtCore.QSize(10, 0))
        self.label_25.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_8.addWidget(self.label_25)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_21.setMinimumSize(QtCore.QSize(91, 0))
        self.label_21.setMaximumSize(QtCore.QSize(91, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.doubleSpinBox_lati_r_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_lati_r_3.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_lati_r_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_lati_r_3.setDecimals(4)
        self.doubleSpinBox_lati_r_3.setObjectName("doubleSpinBox_lati_r_3")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_lati_r_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_26.setMinimumSize(QtCore.QSize(10, 0))
        self.label_26.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_9.addWidget(self.label_26)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_22.setMinimumSize(QtCore.QSize(91, 0))
        self.label_22.setMaximumSize(QtCore.QSize(91, 16777215))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_9.addWidget(self.label_22)
        self.doubleSpinBox_long_d_4 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_long_d_4.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_long_d_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_long_d_4.setDecimals(4)
        self.doubleSpinBox_long_d_4.setObjectName("doubleSpinBox_long_d_4")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_long_d_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.buttonBox_tab_2 = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.buttonBox_tab_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_tab_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_tab_2.setObjectName("buttonBox_tab_2")
        self.verticalLayout_3.addWidget(self.buttonBox_tab_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox_tab_1.accepted.connect(lambda: self.click_on_tab_1(Dialog)) # type: ignore
        self.buttonBox_tab_1.rejected.connect(Dialog.reject) # type: ignore

        self.buttonBox_tab_2.accepted.connect(lambda: self.click_on_tab_2(Dialog)) # type: ignore
        self.buttonBox_tab_2.rejected.connect(Dialog.reject) # type: ignore

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setStyleSheet(_translate("Dialog", "0"))
        self.label_2.setText(_translate("Dialog", "Добавление области сканирования"))
        self.label_10.setText(_translate("Dialog", "Название области: "))
        self.label.setText(_translate("Dialog", "Левый верхний угол:"))
        self.comboBox_NS_1.setItemText(0, _translate("Dialog", "N"))
        self.comboBox_NS_1.setItemText(1, _translate("Dialog", "S"))
        self.label_3.setText(_translate("Dialog", "Градусов"))
        self.label_4.setText(_translate("Dialog", "Минут"))
        self.label_5.setText(_translate("Dialog", "Секунд"))
        self.comboBox_WE_2.setItemText(0, _translate("Dialog", "W"))
        self.comboBox_WE_2.setItemText(1, _translate("Dialog", "E"))
        self.label_12.setText(_translate("Dialog", "Градусов"))
        self.label_13.setText(_translate("Dialog", "Минут"))
        self.label_14.setText(_translate("Dialog", "Секунд"))
        self.label_6.setText(_translate("Dialog", "Правый нижний угол:"))
        self.comboBox_NS_3.setItemText(0, _translate("Dialog", "N"))
        self.comboBox_NS_3.setItemText(1, _translate("Dialog", "S"))
        self.label_7.setText(_translate("Dialog", "Градусов"))
        self.label_8.setText(_translate("Dialog", "Минут"))
        self.label_9.setText(_translate("Dialog", "Секунд"))
        self.comboBox_WE_4.setItemText(0, _translate("Dialog", "W"))
        self.comboBox_WE_4.setItemText(1, _translate("Dialog", "E"))
        self.label_16.setText(_translate("Dialog", "Градусов"))
        self.label_17.setText(_translate("Dialog", "Минут"))
        self.label_18.setText(_translate("Dialog", "Секунд"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Картографический формат"))
        self.label_19.setText(_translate("Dialog", "Левая широта:"))
        self.label_20.setText(_translate("Dialog", "Верхняя долгота:"))
        self.label_21.setText(_translate("Dialog", "Правая широта:"))
        self.label_22.setText(_translate("Dialog", "Нижняя долгота:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Машинный формат"))
