# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_export.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Output_db import Output_db
import json
import pandas as pd
from PyQt5.QtCore import QDate

class Ui_Dialog_export(object):

    def replaceNone(self, data_dict, v, rv):
        for key in data_dict.keys():
            if data_dict[key] == v:
                data_dict[key] = rv
            elif type(data_dict[key]) is dict:
                self.replaceNone(data_dict[key], v, rv)

    def on_click_export(self, dialog):

        if len(self.lineEdit_name_file.text()) == 0:
            return

        print(self.lineEdit_name_file.text())
        print(self.lineEdit_name_ship.text())
        print(self.comboBox_akv.currentText())
        print(self.lineEdit_coun.text())
        print(self.comboBox_type.currentText())
        print("От: " + str(self.dateEdit_ot.date().toPyDate()) + " До: " + str(self.dateEdit_do.date().toPyDate()))
        print(self.comboBox_format.currentText())

        #print("Левая широта: " + str(self.doubleSpinBox_lati_l_1.value()))
        #print("Верхняя долгота: " + str(self.doubleSpinBox_long_u_2.value()))
        #print("Правая широта: " + str(self.doubleSpinBox_lati_r_3.value()))
        #print("Нижняя долгота: " + str(self.doubleSpinBox_long_d_4.value()))

        type_format = self.comboBox_format.currentText()

        type_format_num = 0
        if type_format == "CSV":
            type_format_num = 1
        elif type_format == "JSON":
            type_format_num = 2
        elif type_format == "EXCEL":
            type_format_num = 3

        name = self.lineEdit_name_ship.text()
        name = name.replace(' ', '')
        #akva = self.comboBox.currentText()
        count = self.lineEdit_coun.text()
        count = count.replace(' ', '').upper()
        types = self.comboBox_type.currentText()

        num = 0

        where = ""
        if len(name) > 0:
            names = name.split(',')
            num += 1
            for i in range(0, len(names)):
                where += "t2.name = '" + str(names[i]) + "'"
                if i + 1 != len(names):
                    where += " OR "
        if len(count) > 0:
            if num > 0:
                where += " AND "
            num += 1
            counts = count.split(',')
            for i in range(0, len(counts)):
                where += "t2.flag = '" + str(counts[i]) + "'"
                if i + 1 != len(counts):
                    where += " OR "
        if len(types) > 0:
            if num > 0:
                where += " AND "
            num += 1
            where += "t2.type = '" + str(types) + "'"
        result = ""
        if num > 0:
            result = "AND " + where

        result_out = Output_db.output_visualizer(result, 1)

        for i in range(0, len(result_out)):
            result_out[i]['timedate'] = result_out[i]['timedate'].strftime("%m/%d/%Y, %H:%M:%S")

        if type_format_num == 1:
            strjson = str(result_out).replace("'", '"')
            data_str = json.dumps(strjson)
            data = json.loads(data_str)
            self.replaceNone(data, None, "")
            #print(strjson)
            df = pd.DataFrame(data)
            df.to_csv(str(self.lineEdit_name_file.text()) + ".csv", index=False)
        elif type_format_num == 2:
            with open("C://Users//nikit//PycharmProjects//mapParser//files//" + str(self.lineEdit_name_file.text()) + '.json', 'w') as outfile:
                json.dump(result_out, outfile)
        dialog.reject()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(468, 535)
        Dialog.setMinimumSize(QtCore.QSize(468, 535))
        Dialog.setMaximumSize(QtCore.QSize(468, 535))
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 421, 495))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(33)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(90, 0))
        self.label_10.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.lineEdit_name_file = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_name_file.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_name_file.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_name_file.setObjectName("lineEdit_name_file")
        self.horizontalLayout_7.addWidget(self.lineEdit_name_file)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_name_ship = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_name_ship.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_name_ship.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_name_ship.setObjectName("lineEdit_name_ship")
        self.horizontalLayout.addWidget(self.lineEdit_name_ship)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_akv = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_akv.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_akv.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_akv.setObjectName("comboBox_akv")
        self.comboBox_akv.addItem("")
        self.comboBox_akv.addItem("")
        self.comboBox_akv.addItem("")
        self.comboBox_akv.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_akv)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(90, 0))
        self.label_3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_coun = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_coun.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_coun.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_coun.setObjectName("lineEdit_coun")
        self.horizontalLayout_3.addWidget(self.lineEdit_coun)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(90, 0))
        self.label_4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_type = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_type.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_type.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_type)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.dateEdit_ot = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_ot.setObjectName("dateEdit_ot")
        self.horizontalLayout_6.addWidget(self.dateEdit_ot)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.dateEdit_do = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_do.setObjectName("dateEdit_do")

        d = QDate(2030, 1, 1)

        # setting date to the date edit
        self.dateEdit_do.setDate(d)

        self.horizontalLayout_6.addWidget(self.dateEdit_do)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(90, 0))
        self.label_6.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBox_format = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_format.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_format.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_format.setObjectName("comboBox_format")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_format)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem14)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(lambda: self.on_click_export(Dialog)) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "Экспорт данных"))
        self.label_10.setText(_translate("Dialog", "Название файла: "))
        self.label.setText(_translate("Dialog", "Названия судов: "))
        self.label_2.setText(_translate("Dialog", "Акватория:"))
        self.comboBox_akv.setItemText(0, _translate("Dialog", ""))
        self.comboBox_akv.setItemText(1, _translate("Dialog", "Владивосток"))
        self.comboBox_akv.setItemText(2, _translate("Dialog", "Акватория 1"))
        self.comboBox_akv.setItemText(3, _translate("Dialog", "Акватория 2"))
        self.label_3.setText(_translate("Dialog", "Страны:"))
        self.label_4.setText(_translate("Dialog", "Тип:"))
        self.comboBox_type.setItemText(0, _translate("Dialog", ""))
        self.comboBox_type.setItemText(1, _translate("Dialog", "fishing"))
        self.comboBox_type.setItemText(2, _translate("Dialog", "tag"))
        self.comboBox_type.setItemText(3, _translate("Dialog", "pleasure craft"))
        self.comboBox_type.setItemText(4, _translate("Dialog", "cargo"))
        self.comboBox_type.setItemText(5, _translate("Dialog", "tanker"))
        self.comboBox_type.setItemText(6, _translate("Dialog", "passenger"))
        self.label_7.setText(_translate("Dialog", "Дата"))
        self.label_8.setText(_translate("Dialog", "От:"))
        self.label_9.setText(_translate("Dialog", "До:"))
        self.label_6.setText(_translate("Dialog", "Формат:"))
        self.comboBox_format.setItemText(0, _translate("Dialog", "CSV"))
        self.comboBox_format.setItemText(1, _translate("Dialog", "JSON"))
        self.comboBox_format.setItemText(2, _translate("Dialog", "EXCEL"))
